"""Every line of player-facing text in the game, for the text pass with the dev (NOTES 159):
each string literal in the game's scripts that reads like words, grouped by script and by
the function (or constant) it sits in, with its line number, so the pass can go through
the lot in order. Writes docs/TEXT.md. Stdlib only.

Run from the repo root: python tools/text_inventory.py
A literal counts as text if it has a space, or starts with a capital, or ends in
punctuation, and isn't a path or a node's name. Format strings keep their %s and %d:
those are where the game fills something in.
"""
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), "..")
OUT = os.path.join(ROOT, "docs", "TEXT.md")

LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')
HOME = re.compile(r"^(?:static )?func (\w+)|^const (\w+)|^var (\w+)")
# Code-ish strings that pass the text test anyway: paths, colours, sound ids.
NOT_TEXT = re.compile(r"^(res://|user://|%[a-z0-9_]+$|[0-9a-f]{6}$|ui_|[A-Za-z]+/[A-Za-z])")
# A line naming nodes, audio buses or theme types: its one-word literals are names, not text.
NAMING = re.compile(r"[.]name\b|\bname =|get_node|find_child|\bbus\b|AudioServer|set_stylebox|set_color|[$]|\bnew[(][)]")


def is_text(s: str, line: str) -> bool:
    if len(re.findall(r"[A-Za-z]", s)) < 2 or NOT_TEXT.match(s):
        return False
    if re.fullmatch(r"[A-Za-z]+(%d)?", s) and NAMING.search(line):
        return False
    return " " in s or s[0].isupper() or s[-1] in ".!?"


def scan(path: str) -> list:
    """[(home, line number, text)] for one script, comments skipped."""
    out = []
    home = "(top of the file)"
    with open(path, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            m = HOME.match(line)
            if m:
                home = next(g for g in m.groups() if g)
            before = line.split('"', 1)[0]
            code = line[: line.index("#")] if "#" in before else line # a comment before any string
            for s in LITERAL.findall(code):
                if is_text(s, code):
                    out.append((home, n, s))
    return out


def main() -> None:
    scripts = sorted(f for f in os.listdir(ROOT) if f.endswith(".gd"))
    body = []
    total = 0
    for name in scripts:
        found = scan(os.path.join(ROOT, name))
        if not found:
            continue
        total += len(found)
        body.append(f"\n## {name} ({len(found)})\n")
        last = None
        for home, n, s in found:
            if home != last:
                body.append(f"\n### {home}\n")
                last = home
            body.append(f"- L{n}: {s}")
    head = [
        "# Text",
        "",
        "Every line of player-facing text, generated by `python tools/text_inventory.py` (don't edit",
        "by hand). For the text pass (NOTES 159): the dev rewrites each in their own voice, with",
        "variants. `%s` and `%d` are where the game fills something in; `\\n` is a line break.",
        "",
        f"{total} lines in all. The filter is a guess: a code string may slip in, and a line",
        "built from pieces shows as its pieces.",
    ]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(head + body) + "\n")
    print(f"{total} lines -> docs/TEXT.md")


if __name__ == "__main__":
    main()
